baseurl: "/"
languageCode: "en-us"
title: "miguel codes"
theme: "hugo-tania"
paginate: 6

params:
  # Emoji will show before the blog title on site navbar.
  titleEmoji: 🌵

  # Logo will show before the blog title on site navbar.
  titleLogo:

  # Enable float footnotes.
  # Default to true
  enableFootnotes: false

  siteName: "Miguel's devblog"
  siteDesc: "Posts on Software Development"
  author: "Miguel ORTEGA"

  colorScheme:
    # Enable toggle colorScheme
    # Default to true
    toggle: true
    # Default colorScheme
    # Default to auto
    default: auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow: 10

  # Show your socail information with icon on index bio with `_index.md` content.
  socialOptions:
    dev-to: https://dev.to/mikomatic
    email:
    facebook:
    github: https://github.com/mikomatic
    instagram:
    linkedin:
    medium:
    stack-overflow:
    steam:
    telegram:
    twitter: https://twitter.com/mikomatic
    twitch:
    whatsapp:

  # Comments settings
  comments:
    enabled: true
    provider: giscus

    giscus:
      repo: mikomatic/mortega.dev
      id: R_kgDOGroJ5A
      category:
        name: Announcements
        id: DIC_kwDOGroJ5M4CA58S

menu:
  header:
    - name: Articles
      url: "/articles/"
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "JSON"]