---
title: "Hello World"
date: 2021-02-10T21:20:04+01:00
toc: true
---
:source-highlighter: rouge
:rouge-style: molokai
:icons: font
:sectanchors:
:toc:

== En un mot

Asciidoctor lit du contenu écrit en texte brut, comme présenté dans la partie gauche de l'image ci-dessous, et le convertit en HTML 5, comme présenté dans la partie droite.
Asciidoctor applique une feuille de style par défaut au document HTML 5 afin de fournir une expérience de lecture agréable, clé en main.

== Le traitement d'AsciiDoc

Asciidoctor lit et analyse la syntaxe du texte écrit en AsciiDoc afin de créer une représentation, sous forme d'arbre, à partir de laquelle des templates sont appliqués pour produire de l'HTML 5, du DocBook 5 et des pages de man(uel).

== Asciidoctor est disponible partout où Ruby est disponible

Vous pouvez exécuter Asciidoctor dans la JVM en utilisant JRuby.
Des plugins basés sur AsciidoctorJ permettent d'intégrer le processeur Asciidoctor avec Apache Maven, Gradle ou Javadoc.

Asciidoctor s'exécute également au sein de JavaScript.
Asciidoctor.js est utilisé pour faire fonctionner les extensions AsciiDoc Preview pour Chrome, Atom, Brackets et autres outils web.

== Prérequis

* CRuby (aka MRI) 2.3 - 2.6
* JRuby 9.1 - 9.2
* TruffleRuby (GraalVM)
* Opal (JavaScript)

[CAUTION]
====
Si vous utilisez un environnement Windows dans une autre langue que l'anglais, vous pourriez tomber sur l'erreur `Encoding::UndefinedConversionError` lors du lancement d'Asciidoctor.
Pour corriger ce problème, nous recommandons de changer la page de code en UTF-8 dans votre console :

 chcp 65001

Après ce changement, tous les maux de tête liés à l'Unicode seront derrière vous.
Si vous utilisez un environnement de développement comme Eclipse, assurez-vous de définir l'encodage en UTF-8.
Asciidoctor fonctionne mieux lorsque vous utilisez UTF-8 partout.
====

== Installation

Asciidoctor peut être installé en utilisant (a) un gestionnaire de paquets Linux, (b) Homebrew pour macOS, (c) la commande `gem install` (recommandé pour les utilisateurs Windows), (d) l'image officielle Docker, ou (e) Bundler.

L'avantage d'utiliser le gestionnaire de paquets pour installer la gemme est que l'installation englobe celle des librairies Ruby et RubyGems si elles ne sont pas déjà installées.

=== (a) Gestionnaires de paquets Linux

La version installée par votre gestionnaire de paquets peut ne pas correspondre à la dernière version d'Asciidoctor.
Consulter le dépôt de votre distribution Linux pour connaitre la dernière version disponible d'Asciidoctor en fonction de la version de votre distribution.

* https://pkgs.alpinelinux.org/packages?name=asciidoctor[Alpine Linux (asciidoctor)]
* https://packages.debian.org/sid/asciidoctor[Debian (asciidoctor)]
* https://apps.fedoraproject.org/packages/rubygem-asciidoctor[Fedora (asciidoctor)]
* https://software.opensuse.org/package/rubygem-asciidoctor[OpenSUSE (rubygem-asciidoctor)]
* https://packages.ubuntu.com/search?keywords=asciidoctor[Ubuntu (asciidoctor)]

Si vous souhaitez installer une version plus récente d'Asciidoctor que celle proposée par votre gestionnaire de paquets, suivre <<gem-install,la procédure d'installation gem>>.

==== apk (Alpine Linux)

Pour installer le paquet sur Alpine Linux, ouvrez un terminal et tapez :

 $ sudo apk add asciidoctor

==== APT

Sur Debian et les distributions dérivées de Debian, comme Ubuntu, utilisez APT pour installer Asciidoctor.
Pour installer le paquet, ouvrez un terminal et tapez :

 $ sudo apt-get install -y asciidoctor

==== DNF

Sur les distributions Linux qui utilisent des RPM, comme Fedora, CentOS, et RHEL, utilisez le gestionnaire de paquets DNF pour installer Asciidoctor.
Pour installer le paquet, ouvrez un terminal et tapez :

 $ sudo dnf install -y asciidoctor

=== (b) Homebrew (macOS)

Vous pouvez utiliser Homebrew, le gestionnaire de paquets sur macOS, pour installer Asciidoctor.
Si vous n'avez pas encore installé Homebrew, suivez les instructions sur https://brew.sh/[brew.sh].

Une fois Homebrew installé, vous pouvez installer Asciidoctor.
Ouvrez un terminal et tapez :

 $ brew install asciidoctor

Homebrew installe la gemme `asciidoctor` dans un répertoire spécifique qui est indépendant des gemmes système.

[#gem-install]
=== (c) gem install

Avant d'installer Asciidoctor en utilisant `gem install`, il est recommandé d'utiliser https://rvm.io[RVM] pour installer Ruby dans votre « home » (c'est-à-dire, votre espace utilisateur).
Ensuite, vous pouvez utiliser la commande `gem` pour installer ou mettre à jour la gemme Asciidoctor.
Quand vous utilisez RVM, les gemmes sont installées dans un répertoire isolé du système.

Ouvrez un terminal et tapez :

 $ gem install asciidoctor

Si vous souhaitez installer une version pre-release (c'est-à-dire, une « release candidate »), utilisez :

[source,ruby]
----
require 'sinatra'

get '/hi' do
  "Hello World!"
end
----


NOTE: OK

=== (e) Bundler

. Créez un fichier Gemfile à la racine de votre projet (ou du répertoire courant)
. Ajoutez la gemme `asciidoctor` dans votre fichier Gemfile comme ci-dessous :
+
[subs=attributes+]
----
source 'https://rubygems.org'
gem 'asciidoctor'
# ou spécifier la version explicitement
# gem 'asciidoctor', '{release-version}'
----

. Sauvegardez le fichier Gemfile
. Ouvrez un terminal et installez la gemme en utilisant :

 $ bundle

Pour mettre à jour la gemme, spécifiez la nouvelle version dans le fichier Gemfile et exécutez `bundle` à nouveau.
Utiliser `bundle update` *n*'est *pas* recommandé car les autres gemmes seront également mises à jour, ce qui n'est pas forcément le résultat voulu.

== Mise à jour

Si vous avez installé Asciidoctor en utilisant votre gestionnaire de paquets, votre système d'exploitation est surement configuré pour mettre à jour automatiquement les paquets, si tel est le cas vous n'avez pas besoin de mettre à jour manuellement Asciidoctor.

=== apk (Alpine Linux)

Pour mettre à jour Asciidoctor, tapez :

 $ sudo apk add -u asciidoctor
